services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./djangoapp:/djangoapp
    command:
      sh -c "python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    volumes:
      - ./djangoapp:/djangoapp

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./djangoapp:/djangoapp
    links:
      - redis
    depends_on:
      - redis
